version: '2'

services:
  zookeeper:
    image: "jplock/zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: "wurstmeister/kafka:0.10.0.0"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    links:
      - "zookeeper"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock